version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  labels:
  - pr/dependencies
  - kind/chore
  - language/go
  ignore:
  - dependency-name: k8s.io/api
    versions:
    - ">= 0.20.a"
    - "< 0.21"
  - dependency-name: k8s.io/apimachinery
    versions:
    - ">= 0.20.a"
    - "< 0.21"
  - dependency-name: k8s.io/client-go
    versions:
    - ">= 0.20.a"
    - "< 0.21"
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  labels:
  - kind/chore
  - pr/dependencies
- package-ecosystem: npm
  directory: "/provider-ui"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  reviewers:
  - nebula-aac
  labels:
  - kind/chore
  - pr/dependencies
- package-ecosystem: gomod
  directory: "/scripts/component_generation"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  labels:
  - pr/dependencies
  - kind/chore
  - language/go
- package-ecosystem: gomod
  directory: "/scripts/component_updation"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  labels:
  - pr/dependencies
  - kind/chore
  - language/go
