# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: v1alpha3

# Update the "output" and "include-tags" based on the resource for which code generation needs to be invoked.
output: models/v1alpha3/relationships.go 
generate:
  models: true
import-mapping:
  "#/components/schemas/catalog_data": "github.com/khulnasoft/meshkit/models/catalog/v1alpha1"
  "./common/core.yml": "github.com/meshplay/schemas/models/core"
  "../core.json": "github.com/meshplay/schemas/models/core"
  "../v1beta1/model.json": "github.com/meshplay/schemas/models/v1beta1"

output-options:
  skip-prune: true
