openapi: 3.0.0
info:
  title: Meshplay Cloud
  description: Documentation for meshplay Cloud REST APIs
  contact:
    email: support@khulnasoft.com
  version: v0.6.394
servers:
  - url: https://meshplay.khulnasoft.com
    description: Meshplay Cloud production server URL
  - url: https://staging-meshplay.khulnasoft.com
    description: Meshplay Cloud staging server URL
  - url: http://localhost:9876
    description: Meshplay Cloud development server URL (controlled via PORT environment variable)
security:
  - jwt: []
tags:
  - name: patterns
    description: APIs for patterns
components:
  securitySchemes:
    jwt:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  schemas:
    meshplayPatternResource:
      properties:
        id:
          $ref: ./common/core.yml#/components/schemas/id
        user_id:
          $ref: ./common/core.yml#/components/schemas/id
        name:
          $ref: ./common/core.yml#/components/schemas/text
          description: Name
        namepace:
          $ref: ./common/core.yml#/components/schemas/text
          description: Namespace
        type:
          $ref: ./common/core.yml#/components/schemas/text
          description: Type
        oam_type:
          $ref: ./common/core.yml#/components/schemas/text
          description: OAM type
        deleted:
          type: boolean
        created_at:
          $ref: ./common/core.yml#/components/schemas/time
        updated_at:
          $ref: ./common/core.yml#/components/schemas/time
    meshplayPatternResourcePage:
      allOf:
        - $ref: ./common/core.yml#/components/schemas/resultsPage
        - type: object
          properties:
            resources:
              type: array
              items:
                $ref: "#/components/schemas/meshplayPatternResource"
    meshplayPattern:
      properties:
        id:
          $ref: ./common/core.yml#/components/schemas/id
        user_id:
          $ref: ./common/core.yml#/components/schemas/id
        pattern_file:
          $ref: ../v1beta1/designs.json
          description: Pattern file
          x-oapi-codegen-extra-tags:
            gorm: type:bytes;serializer:json
        name:
          $ref: ./common/core.yml#/components/schemas/text
          description: Pattern Name
        location:
          $ref: ./common/core.yml#/components/schemas/map_object
        visibility:
          $ref: ./common/core.yml#/components/schemas/text
        catalog_data:
          $ref: ../v1alpha1/catalog_data.json
        created_at:
          $ref: ./common/core.yml#/components/schemas/time
        updated_at:
          $ref: ./common/core.yml#/components/schemas/time
    meshplayPatternPage:
      allOf:
        - $ref: ./common/core.yml#/components/schemas/resultsPage
        - type: object
          properties:
            patterns:
              type: array
              items:
                $ref: "#/components/schemas/meshplayPattern"
    deletePatternModel:
      properties:
        id:
          $ref: ./common/core.yml#/components/schemas/id
        name:
          description: Pattern name
          $ref: ./common/core.yml#/components/schemas/text

  requestBodies:
    meshplayPatternResource:
      description: Body for upserting meshplay pattern resource
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/meshplayPatternResource"
    meshplayPatternRequestBody:
      description: Body for upserting meshplay pattern
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              url:
                $ref: ./common/core.yml#/components/schemas/endpoint
              path:
                $ref: ./common/core.yml#/components/schemas/text
              save:
                type: boolean
              pattern_data:
                $ref: "#/components/schemas/meshplayPattern"
    meshplayPatternDeleteRequestBody:
      description: Body for deleting meshplay pattern
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              patterns:
                type: array
                items:
                  $ref: "#/components/schemas/deletePatternModel"

    designShare:
      description: Body for sharing design
      required: true
      content:
        application/json:
          schema:
            properties:
              emails:
                $ref: ./common/core.yml#/components/schemas/emails
              id:
                $ref: ./common/core.yml#/components/schemas/id
              content_type:
                type: string
              share:
                type: boolean
            required: [emails, id, content_type, share]

# paths:
#   #designs
#   /api/content/patterns/resource:
#     post:
#       tags:
#         - patterns
#       operationId: UpsertPatternResource
#       summary: Upsert Pattern resource
#       description: It will insert the pattern resource if not present else it will update the matching entry
#       requestBody:
#         $ref: "#/components/requestBodies/meshplayPatternResource"
#       responses:
#         "200":
#           description: Meshplay pattern resource
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/meshplayPatternResource"
#         "401":
#           $ref: ./common/responses.yml#/401
#         "500":
#           $ref: ./common/responses.yml#/500
#     get:
#       tags:
#         - patterns
#       operationId: GetPatternResources
#       summary: Get Pattern resources
#       description: Get paginated pattern resources
#       parameters:
#         - $ref: ./common/parameters.yml#/components/parameters/page
#         - $ref: ./common/parameters.yml#/components/parameters/page_size
#         - $ref: ./common/parameters.yml#/components/parameters/search
#         - $ref: ./common/parameters.yml#/components/parameters/order
#         - $ref: ./common/parameters.yml#/components/parameters/namespace
#         - $ref: ./common/parameters.yml#/components/parameters/type
#         - $ref: ./common/parameters.yml#/components/parameters/oamType
#         - $ref: ./common/parameters.yml#/components/parameters/name
#           description: Name
#       responses:
#         "200":
#           description: Meshplay pattern resources
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/meshplayPatternResourcePage"
#         "401":
#           $ref: ./common/responses.yml#/401
#         "500":
#           $ref: ./common/responses.yml#/500
#   /api/content/patterns/resource/{id}:
#     get:
#       tags:
#         - patterns
#       operationId: GetPatternResource
#       summary: Pattern Resource by ID
#       description: Get Pattern Resource By ID
#       parameters:
#         - $ref: ./common/parameters.yml#/components/parameters/id
#       responses:
#         "200":
#           description: Meshplay pattern resource associated with id
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/meshplayPatternResource"
#         "400":
#           $ref: ./common/responses.yml#/400
#         "401":
#           $ref: ./common/responses.yml#/401
#         "404":
#           $ref: ./common/responses.yml#/404
#         "500":
#           $ref: ./common/responses.yml#/500
#     delete:
#       tags:
#         - patterns
#       operationId: DeletePatternResource
#       summary: Delete pattern resource
#       description: Delete pattern resource associated with id
#       parameters:
#         - $ref: ./common/parameters.yml#/components/parameters/id
#       responses:
#         "200":
#           description: Deleted meshplay pattern resource associated with id
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/meshplayPatternResource"
#         "400":
#           $ref: ./common/responses.yml#/400
#         "401":
#           $ref: ./common/responses.yml#/401
#         "404":
#           $ref: ./common/responses.yml#/404
#         "500":
#           $ref: ./common/responses.yml#/500
#   /api/content/patterns:
#     post:
#       tags:
#         - patterns
#       operationId: UpsertPattern
#       summary: Upsert Pattern
#       description: It will insert the pattern if not present else it will update the matching entry
#       requestBody:
#         $ref: "#/components/requestBodies/meshplayPatternRequestBody"
#       responses:
#         "200":
#           description: Upserted pattern
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: "#/components/schemas/meshplayPattern"
#         "400":
#           $ref: ./common/responses.yml#/400
#         "401":
#           $ref: ./common/responses.yml#/401
#         "500":
#           $ref: ./common/responses.yml#/500
#     get:
#       tags:
#         - patterns
#       operationId: GetPatterns
#       summary: Get Patterns
#       description: Get paginated patterns
#       parameters:
#         - $ref: ./common/parameters.yml#/components/parameters/page
#         - $ref: ./common/parameters.yml#/components/parameters/page_size
#         - $ref: ./common/parameters.yml#/components/parameters/search
#         - $ref: ./common/parameters.yml#/components/parameters/order
#       responses:
#         "200":
#           description: Patterns
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/meshplayPatternPage"
#         "401":
#           $ref: ./common/responses.yml#/401
#         "500":
#           $ref: ./common/responses.yml#/500
#     delete:
#       tags:
#         - patterns
#       operationId: DeletePatterns
#       summary: Delete patterns
#       description: Delete patterns with the provided ids
#       requestBody:
#         $ref: "#/components/requestBodies/meshplayPatternDeleteRequestBody"
#       responses:
#         "200":
#           description: Deleted pattern
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/meshplayPattern"
#         "400":
#           $ref: ./common/responses.yml#/400
#         "401":
#           $ref: ./common/responses.yml#/401
#         "500":
#           $ref: ./common/responses.yml#/500
#   /api/content/patterns/{id}:
#     get:
#       tags:
#         - patterns
#       operationId: GetPattern
#       summary: Get pattern by ID
#       description: Get pattern by ID
#       parameters:
#         - $ref: ./common/parameters.yml#/components/parameters/id
#       responses:
#         "200":
#           description: Pattern associated with ID
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/meshplayPattern"
#         "400":
#           $ref: ./common/responses.yml#/400
#         "401":
#           $ref: ./common/responses.yml#/401
#         "404":
#           $ref: ./common/responses.yml#/404
#         "500":
#           $ref: ./common/responses.yml#/500
#     delete:
#       tags:
#         - patterns
#       operationId: DeletePattern
#       summary: Delete pattern by ID
#       description: Delete pattern associated with ID
#       parameters:
#         - $ref: ./common/parameters.yml#/components/parameters/id
#       responses:
#         "200":
#           description: Deleted pattern
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/meshplayPattern"
#         "400":
#           $ref: ./common/responses.yml#/400
#         "401":
#           $ref: ./common/responses.yml#/401
#         "404":
#           $ref: ./common/responses.yml#/404
#         "500":
#           $ref: ./common/responses.yml#/500
#   /api/content/patterns/clone/{id}:
#     post:
#       tags:
#         - patterns
#       operationId: ClonePattern
#       summary: Clone pattern
#       description: Clone pattern associated with ID
#       parameters:
#         - $ref: ./common/parameters.yml#/components/parameters/id
#       requestBody:
#         description: Body for cloning design
#         required: true
#         content:
#           application/json:
#             schema:
#               properties:
#                 name:
#                   type: string
#               required:
#                 - name
#       responses:
#         "200":
#           $ref: ./common/responses.yml#/200
#         "400":
#           $ref: ./common/responses.yml#/400
#         "401":
#           $ref: ./common/responses.yml#/401
#         "500":
#           $ref: ./common/responses.yml#/500
#   /api/content/design/share:
#     post:
#       tags:
#         - patterns
#       operationId: HandleShare
#       summary: Design Share
#       description: Share design with others
#       requestBody:
#         $ref: "#/components/requestBodies/designShare"
#       responses:
#         "200":
#           $ref: ./common/responses.yml#/200
#         "401":
#           $ref: ./common/responses.yml#/401
#         "403":
#           description: Only owner have access to changing sharing mode
#           content:
#             text/plain:
#               schema:
#                 type: string
#         "500":
#           $ref: ./common/responses.yml#/500
